[package]
name = "cerebro"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
poise = "0.5.5"
shuttle-poise = "0.35.2"
shuttle-runtime = "0.35.2"
shuttle-secrets = "0.35.2"
tracing = "0.1.37"
tokio = "1.28.2"
